FROM ubuntu:noble

WORKDIR /var/www/html

RUN apt-get update -y
RUN apt-get upgrade -y


RUN apt-get install -y \
    apt-utils \
    apache2 \
    apache2-utils \
    php \
    libapache2-mod-php\
    php-curl \
    php-bcmath \ 
    php-json \
    php-mysql \
    php-mbstring \ 
    mysql-client \
    php-xml \
    php-tokenizer \ 
    php-zip \
    composer    


RUN a2enmod rewrite    


# COPY . /var/www/html/

# RUN chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache
# RUN chmod -R 775 /var/www/html/storage /var/www/html/bootstrap/cache

EXPOSE 80

# Copy site into place.
ADD aggregator /var/www/html

# RUN chown -R www-data:www-data /var/www/aggregator
# RUN chmod -R 775 /var/www/aggregator


# Update the default apache site with the config we created.
ADD aggregator.conf /etc/apache2/sites-enabled/000-default.conf

CMD ["apache2ctl", "-D","FOREGROUND"]