version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/apache/Dockerfile
    container_name: laravel-apache
    volumes:
      - ./laravel-app:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - db
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: laravel-mysql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel

networks:
  laravel:

volumes:
  mysql_data:
